resources:
- name: openbank_apis
  type: solutions.api
  properties:
    inputs:
    - name: org
      prompt: Edge Org name
    - name: env
      prompt: Edge Org Environment
    - name: token
      prompt: Edge Auth token
    - name: usergrid_org
      prompt: App services org name
    - name: usergrid_app
      prompt: App services app name
    - name: usergrid_client_id
      prompt: App services App Client Id
    - name: usergrid_secret
      prompt: App services App Client Secret
    configurations:
    - env: test
      external_url: http://some-test.com
    - env : prod
      externam_url: http://some-prod.com

    script: gulpfile.js
    basePath: /Users/gauthamvk/apigee/git/openbank-fork
    dependencies:
#    - name: oauth
#      type: proxy
#      url: git@revision.aeip.apigee.net:solution-commons/oauth.git
#      version: v1.0.0
    - name: session
      type: proxy
      url: git@revision.aeip.apigee.net:solution-commons/session.git
      version: v1.0.0
#    - name: oauth
#      type: userinfo
#      url: git@revision.aeip.apigee.net:solution-commons/oauth.git
#      version: v1.0.0
#    - name: authentication-connector
#      type: proxy
#      url: git@revision.aeip.apigee.net:solution-commons/authentication-connector.git
#     version: v1.0.0
    edgeOrg:
      orgName:'{{organization}}'
      env:'{{environment}}'
      token:'{{token}}'
    dataSources:
    - name: default
      orgName: '{{usergrid_org}}'
      appName: '{{usergrid_app}}'
      appClientId: '{{usergrid_client_id}}'
      appSecret: '{{usergrid_secret}}'
    subResources:
    - name: cacheResources
      type: cache
      items:
      - name: consent-session-cache
        payload: '{ "name": "consent-session-cache"}'
      - name: application-session-cache
        payload: '{ "name": "application-session-cache"}'
      - name: sms-token-cache
        payload: '{ "name": "sms-token-cache"}'
    - name: replaceorgvalues
      type: configSubstitutions
      items:
      - name: baas_org
        filePaths: ['src/gateway/accounts-connector/target/apiproxy/policies/Assign.TargetURL.xml','src/gateway/locations-connector/target/apiproxy/policies/Assign.TargetURL.xml','src/gateway/products-connector/target/apiproxy/policies/Assign.TargetURL.xml','src/gateway/transfers-connector/target/apiproxy/policies/Callout.AddTransactionToAccount.xml','src/gateway/transfers-connector/target/apiproxy/targets/default.xml','src/gateway/userinfo/target/apiproxy/policies/Callout.GetUserDetails.xml','src/gateway/authentication-connector/target/apiproxy/targets/default.xml']
        value: usergrid_org
      - name: baas_app
        filePaths: ['src/gateway/accounts-connector/target/apiproxy/policies/Assign.TargetURL.xml','src/gateway/locations-connector/target/apiproxy/policies/Assign.TargetURL.xml','src/gateway/products-connector/target/apiproxy/policies/Assign.TargetURL.xml','src/gateway/transfers-connector/target/apiproxy/policies/Callout.AddTransactionToAccount.xml','src/gateway/transfers-connector/target/apiproxy/targets/default.xml','src/gateway/userinfo/target/apiproxy/policies/Callout.GetUserDetails.xml','src/gateway/authentication-connector/target/apiproxy/targets/default.xml']
        value: usergrid_app
      - name: org
        filePaths: ['src/gateway/oauth/target/apiproxy/policies/Assign-JWT-Payload.xml','src/gateway/oauth/target/apiproxy/policies/Assign-ID-Token-Payload-authorization_code-flow.xml','src/gateway/oauth/target/apiproxy/policies/Redirect-Login-Application.xml','src/gateway/transfers/target/apiproxy/policies/Assign.RedirectConsentApp.xml']
        value: org
      - name: env
        filePaths: ['src/gateway/oauth/target/apiproxy/policies/Assign-JWT-Payload.xml','src/gateway/oauth/target/apiproxy/policies/Assign-ID-Token-Payload-authorization_code-flow.xml','src/gateway/oauth/target/apiproxy/policies/Redirect-Login-Application.xml','src/gateway/transfers/target/apiproxy/policies/Assign.RedirectConsentApp.xml']
        value: env
    - name: bank_apis
      type: proxy
      items:
      - name: accounts
      - name: accounts-connector
      - name: authentication-connector
      - name: locations
      - name: locations-connector
      - name: oauth
      - name: session
      - name: sms-token
      - name: transfers
      - name: transfers-connector
      - name: userinfo

    - name: developers
      type: developer
      items:
      - payload: '{"email":"openbank@apigee.net", "firstName":"OpenBank","lastName":"Developer","userName":"openbank"}'
        email: openbank@apigee.net
    - name: apiProducts
      type: product
      items:
      - payload: '{"approvalType":"auto", "displayName":"Open Data APIs","name":"open_data_apis","environments":["test","prod"],"scopes":["openid", "atms", "branches"], "proxies":["oauth", "locations"]}'
        name: open_data_apis
      - payload: '{"approvalType":"auto", "displayName":"Payment Transfer APIs","name":"payment_transfer_apis","environments":["test","prod"],"scopes":["openid", "accounts", "transfer", "payment"], "proxies":["oauth", "transfers", "accounts"]}'
        name: payment_transfer_apis
      - payload: '{"approvalType":"auto", "displayName":"Account Access APIs","name":"account_access_apis","environments":["test","prod"],"scopes":["openid", "accounts", "accounts-info", "accounts-balance", "accounts-transactions"], "proxies":["oauth", "accounts"]}'
        name: account_access_apis
      - payload: '{"approvalType":"auto", "attributes":[{"name":"access","value":"private"}], "displayName":"Internal Consent APIs","name":"internal_consent_apis","environments":["test","prod"],"scopes":[], "proxies":["session", "sms-token", "authentication-connector", "oauth"]}'
        name: internal_consent_apis
    - name: developerApps
      type: app
      items:
      - name: AISP_App
        payload: '{"name":"AISP_App","callback":"http://apigee.com/about","email":"openbank@apigee.net","apiProducts":"account_access_apis"}'
      - name: PISP_App
        payload: '{"name":"PISP_App","callback":"http://apigee.com/about","email":"openbank@apigee.net","apiProducts":"payment_transfer_apis"}'
      - name: Opendata_App
        payload: '{"name":"Opendata_App","callback":"http://apigee.com/about","email":"openbank@apigee.net","apiProducts":"open_data_apis"}'
      - name: internal_consent_app
        payload: '{"name":"internal_consent_app","callback":"http://apigee.com/about","email":"openbank@apigee.net","apiProducts":"internal_consent_apis"}'
        assignResponse:
        - from: consumerKey
          to: apiKey
    - name: replace_consent_app_key
      type: configSubstitutions
      items:
      - name: consent_app_key
        filePaths: ['src/gateway/consent-app/target/apiproxy/resources/node/config.json','src/gateway/consent-app-transfers/target/apiproxy/resources/node/config.json']
        value: apiKey
      - name: org
        filePaths: ['src/gateway/consent-app/target/apiproxy/resources/node/config.json','src/gateway/consent-app-transfers/target/apiproxy/resources/node/config.json']
        value: org
      - name: env
        filePaths: ['src/gateway/consent-app/target/apiproxy/resources/node/config.json','src/gateway/consent-app-transfers/target/apiproxy/resources/node/config.json']
        value: env
    - name: consent_apis
      type: proxy
      items:
      - name: consent-app
      - name: consent-app-transfers


